# Generated by Django 4.1.3 on 2022-12-13 10:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('quickstart', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='snippet',
            old_name='language',
            new_name='langauage',
        ),
    ]
