# Generated by Django 4.1.3 on 2022-12-14 07:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quickstart', '0005_snippet_owner'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='snippet',
            name='owner',
        ),
        migrations.AlterField(
            model_name='snippet',
            name='highlighted',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
