# Generated by Django 4.1.3 on 2022-12-14 08:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quickstart', '0006_remove_snippet_owner_alter_snippet_highlighted'),
    ]

    operations = [
        migrations.CreateModel(
            name='User_1',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=100, null=True)),
                ('email', models.CharField(blank=True, max_length=100, null=True)),
            ],
        ),
    ]
