# Generated by Django 4.1.4 on 2022-12-20 05:50

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('emp_name', models.CharField(blank=True, max_length=100, null=True)),
                ('emp_id', models.BigIntegerField()),
                ('emp_email', models.EmailField(max_length=100)),
                ('emp_location', models.CharField(blank=True, max_length=100, null=True)),
                ('emp_phone', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=100, null=True)),
                ('age', models.PositiveIntegerField()),
                ('email', models.EmailField(help_text='@gmail.com', max_length=100)),
                ('phone', models.IntegerField()),
            ],
        ),
    ]
