# Generated by Django 4.1.4 on 2022-12-20 12:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quickstart_1', '0002_highscore'),
    ]

    operations = [
        migrations.CreateModel(
            name='Hospital',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hos_name', models.CharField(blank=True, max_length=100, null=True)),
                ('hos_type', models.CharField(blank=True, max_length=100, null=True)),
                ('hos_location', models.CharField(blank=True, max_length=100, null=True)),
                ('hos_department', models.CharField(blank=True, max_length=100, null=True)),
            ],
        ),
    ]
