# Generated by Django 4.1.4 on 2022-12-20 15:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('quickstart_1', '0005_hospital_1_patient_medical_record_doctor'),
    ]

    operations = [
        migrations.AlterField(
            model_name='doctor',
            name='hos_doc',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='doc_hospital', to='quickstart_1.hospital_1'),
        ),
        migrations.AlterField(
            model_name='medical_record',
            name='med_p',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='patient', to='quickstart_1.patient'),
        ),
        migrations.AlterField(
            model_name='patient',
            name='hos_p',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='hospital_1', to='quickstart_1.hospital_1'),
        ),
    ]
